steps:
  - name: Tweet
    uses: snow-actions/tweet@v1.2.0
    with:
      status: |
    env:
       CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
       CONSUMER_API_SECRET_KEY: ${{ secrets.TWITTER_CONSUMER_API_SECRET_KEY }}
       ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
       ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
    steps:
        - uses: actions/checkout@v3
        - name: Tweet summary
          id: summary
          uses: snow-actions/tweet@v1.2.0
          with:
           status: |
             Bill Gates jet location!
           media_paths: |
              shot.png
  - name: Tweet details
    uses: IDK
    with:
        status: |
            Additional information
     in_reply_to_status_id: ${{fromJSON(steps.summary.outputs.response).id_str}}
